apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bqeq10kfz-go 
  janus-idp.io/tekton: bqeq10kfz-go
  backstage.io/kubernetes-id: bqeq10kfz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bqeq10kfz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  