apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bqeq10kfz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bqeq10kfz-go 
  name: bqeq10kfz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bqeq10kfz-go 
